=== ngadzheva/HotelsCatalogue/XML_HotelsCatalogue.dtd
<?xml version="1.0" encoding="utf-8"?>
	<!ELEMENT catalogue (regions, chains, hotels)>
	<!ELEMENT regions (region+)>
	<!ELEMENT region (region_name)>
	<!ATTLIST region regionID ID #REQUIRED>
	<!ATTLIST region hotelRef IDREFS #IMPLIED>
	<!ELEMENT region_name (#PCDATA)>
	<!ELEMENT chains (chain+)>
	<!ELEMENT chain (chain_name, chain_description?, chain_logo?)>
	<!ATTLIST chain chainID ID #REQUIRED>
	<!ATTLIST chain hotelRef IDREFS #IMPLIED>
	<!ELEMENT chain_name (#PCDATA)>
	<!ELEMENT chain_description (#PCDATA)>
	<!ELEMENT chain_logo (logo?)>
	<!ELEMENT logo EMPTY>
	<!ATTLIST logo href ENTITY #REQUIRED>
	<!ELEMENT hotels (hotel+)>
	<!ELEMENT hotel (hotel_name, category, hotel_type, address, phone?, email?, site?, description?, more_info?, rooms?, image?)>
	<!ATTLIST hotel photo ENTITY #IMPLIED>
	<!ATTLIST hotel hotelID ID #REQUIRED>
	<!ATTLIST hotel chainRef IDREF #IMPLIED>
	<!ATTLIST hotel regionRef IDREF #IMPLIED>
	<!ELEMENT hotel_name (#PCDATA)>
	<!ELEMENT category (#PCDATA)>
	<!ELEMENT hotel_type (#PCDATA)>
	<!ELEMENT address (city, street?)>
	<!ELEMENT city (#PCDATA)>
	<!ELEMENT street (#PCDATA)>
	<!ELEMENT phone (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT site (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT more_info (service)*>
	<!ELEMENT service (#PCDATA | characteristic)*>
	<!ELEMENT characteristic (#PCDATA)>
	<!ATTLIST characteristic type CDATA #IMPLIED>
	<!ELEMENT rooms (rooms_description?, rooms_images?, room+)>
	<!ELEMENT rooms_description (#PCDATA)>
	<!ELEMENT rooms_images (room_image+)>
	<!ELEMENT room_image (image_src)>
	<!ATTLIST room_image type CDATA #IMPLIED>
	<!ELEMENT image_src EMPTY>
	<!ATTLIST image_src href ENTITY #REQUIRED>
	<!ELEMENT image (src)>
	<!ELEMENT src EMPTY>
	<!ATTLIST src href ENTITY #REQUIRED>
	<!ELEMENT room (type, price)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT price (season)>
	<!ELEMENT season (low?, medium*, high?, all?)>
	<!ELEMENT low (#PCDATA)>
	<!ELEMENT medium (#PCDATA)>
	<!ATTLIST medium type CDATA #IMPLIED>
	<!ELEMENT high (#PCDATA)>
	<!ELEMENT all (#PCDATA)>
	<!NOTATION jpg PUBLIC "jpg viewer">

=== ngadzheva/HotelsCatalogue/XML_HotelsCatalogue.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="XML_HotelsCatalogue.xsl"?>

<!DOCTYPE catalogue SYSTEM "XML_HotelsCatalogue.dtd" [
	<!ENTITY history SYSTEM "images/history/history.jpg" NDATA jpg>
	<!ENTITY historyRoom1 SYSTEM "images/history/room1.jpg" NDATA jpg>
	<!ENTITY historyRoom2 SYSTEM "images/history/room2.jpg" NDATA jpg>
	<!ENTITY lionBansko SYSTEM "images/lionBansko/lionBansko.jpg" NDATA jpg>
	<!ENTITY lionBanskoRoom1 SYSTEM "images/lionBansko/room1.jpg" NDATA jpg>
	<!ENTITY lionBanskoRoom2 SYSTEM "images/lionBansko/room2.jpg" NDATA jpg>
	<!ENTITY lionSunnyBeach SYSTEM "images/lionSunnyBeach/lionSunnyBeach.jpg" NDATA jpg>
	<!ENTITY lionSunnyBeachRoom1 SYSTEM "images/lionSunnyBeach/room1.jpg" NDATA jpg>
	<!ENTITY lionSunnyBeachRoom2 SYSTEM "images/lionSunnyBeach/room2.jpg" NDATA jpg>
	<!ENTITY lionSof SYSTEM "images/lionSofia/lionSofia.jpg" NDATA jpg>
	<!ENTITY lionSofRoom1 SYSTEM "images/lionSofia/room1.jpg" NDATA jpg>
	<!ENTITY lionSofRoom2 SYSTEM "images/lionSofia/room2.jpg" NDATA jpg>
	<!ENTITY ARONIA SYSTEM "images/aroniaBeach/AroniaBeach.jpg" NDATA jpg>
	<!ENTITY ARONIARoom1 SYSTEM "images/aroniaBeach/room1.jpg" NDATA jpg>
	<!ENTITY ARONIARoom2 SYSTEM "images/aroniaBeach/room2.jpg" NDATA jpg>
	<!ENTITY ATLASGoldenSands SYSTEM "images/atlas/Atlas.jpg" NDATA jpg>
	<!ENTITY ATLASGoldenSandsRoom1 SYSTEM "images/atlas/room1.jpg" NDATA jpg>
	<!ENTITY ATLASGoldenSandsRoom2 SYSTEM "images/atlas/room2.jpg" NDATA jpg>
	<!ENTITY ASTERA SYSTEM "images/astera/Astera.jpg" NDATA jpg>
	<!ENTITY ASTERARoom1 SYSTEM "images/astera/room1.jpg" NDATA jpg>
	<!ENTITY ASTERARoom2 SYSTEM "images/astera/room2.jpg" NDATA jpg>
	<!ENTITY ROSTOV SYSTEM "images/rostov/rostov.jpg" NDATA jpg>
	<!ENTITY ROSTOVRoom1 SYSTEM "images/rostov/room1.jpg" NDATA jpg>
	<!ENTITY ROSTOVRoom2 SYSTEM "images/rostov/room2.jpg" NDATA jpg>
	<!ENTITY lionHotels SYSTEM "images/logos/lionLogo.jpg" NDATA jpg>
	<!ENTITY AHotels SYSTEM "images/logos/aHotelsLogo.jpg" NDATA jpg>
]>

<catalogue>

<!--==========================Regions=================================-->

	<regions>
		<region regionID = "BA" hotelRef="LionBansko ASTERABan">
			<region_name>Банско</region_name>
		</region>
		
		<region regionID = "SB" hotelRef="LionSunnyBeach ARONIABeach">
			<region_name>Слънчев бряг</region_name>
		</region>
		
		<region regionID = "CO" hotelRef="LionSof">
			<region_name>София</region_name>
		</region>
		
		<region regionID = "XA" hotelRef="Hist">
			<region_name>Хасково</region_name>
		</region>
		
		<region regionID = "EN" hotelRef="ROSTOVPle">
			<region_name>Плевен</region_name>
		</region>
		
		<region regionID = "GS" hotelRef="ATLASGS">
			<region_name>Златни пясъци</region_name>
		</region>
	</regions>
	
<!--==========================Chains=================================-->
	
	<chains>
		<chain chainID = "Lion" hotelRef="LionBansko LionSof LionSunnyBeach">
			<chain_name>Lion Hotels</chain_name>
			<chain_description>
				Хотели ЛИОН България е една от малкото български хотелски вериги, които се доказаха на пазара с качество, комфорт и отлично обслужване. Първият хотел от веригата – Хотел Лион София, отваря през Април 2004 г., след него отварят врати и хотел Лион Боровец – Декември 2004 г., Хотел Лион Слънчев Бряг – Май 2005 г., и хотел Лион Банско – Декември 2005 г. С Хотели ЛИОН България можете да изберете почивка на море или на планина, да организирате фирмено или семейно събитие. Екип от професионалисти ще изготви индивидуална оферта, за да удовлетвори всички Ваши нужди и изисквания.	
			</chain_description>
			<chain_logo>
				<logo href="lionHotels"/>
			</chain_logo>
		</chain>
		<chain chainID = "A" hotelRef="ASTERABan ARONIABeach ATLASGS">
			<chain_name>A Hotels</chain_name>
			<chain_description>
				A HOTELS e създадена през 2004, като част от портфолиото на "Св. Св. Константин и Елена холдинг" АД и включва четиризвездни хотели, съчетаващи в себе си стилен интериор, уникално местоположение и ексклузивни услуги.
				Хотелите са разположени в едни от най-добрите и атрактивни туристически дестинации в България.
				Независимо от целта на Вашето пътуване – за  почивка или бизнес -  избирайки хотели, част от A HOTELS, Вие ще се насладите на неповторимата атмосфера на лукс и комфорт, ще получите специално отношение, насочено лично и само към Вас.
			</chain_description>
			<chain_logo>
				<logo href="AHotels"/>
			</chain_logo>
		</chain>
	</chains>
	
<!--=========================Hotels===================================-->
	
	<hotels>
	
<!--======================HotelRestaurantHistory======================-->
	
		<hotel hotelID="Hist" regionRef="XA">
			<hotel_name>Hotel Restaurant History</hotel_name>
			<category>3-звезден</category>
			<hotel_type>Хотел-ресторант</hotel_type>
			<address>
				<city>Хасково</city>
				<street>Парк Кенана</street>
			</address>
			<phone>088 911 1999</phone>
			<email>hotel.history@abv.bg</email>
			<description>
				Хотел - ресторант History, разположен в спокойствието на парк Кенана, предлага уютна обстановка за вашия комфорт и релаксация. Хотелът предоставя лукс и комфорт в 12 двойни стаи и апартаменти с характерен тематичен дизай, всяка от която със специфично наименование. 
			</description>
			<more_info>
				<service>
					Двор / Градина
					<characteristic>Тераса</characteristic>
					<characteristic>Градина</characteristic>
				</service>
			
				<service>
					Басейн и уелнес
					<characteristic>Басейн</characteristic>
					<characteristic>Масаж на цяло тяло</characteristic>
					<characteristic>Масаж на ръце</characteristic>
					<characteristic>Масаж на глава</characteristic>
					<characteristic>Масаж на стъпала</characteristic>
					<characteristic>Масаж на шия</characteristic>
					<characteristic>Масаж на гръб</characteristic>
					<characteristic>Открит плувен басейн</characteristic>
					<characteristic>Турска/Парна баня</characteristic>
					<characteristic>Масаж (допълнително заплащане)</characteristic>
					<characteristic>Сауна</characteristic>
				</service>
				
				<service>
					Домашни любимци
					<characteristic type="forbidden">Домашни любимци са забранени.</characteristic>
				</service>	
				
				<service>
					Дейности
					<characteristic>Безплатни велосипеди</characteristic>
					<characteristic>Туризъм</characteristic>
				</service>	
				
				<service>
					Храни и напитки
					<characteristic>Ресторант (а-ла-карт)</characteristic>
				</service>	
				
				<service>
					Интернет
					<characteristic type="free">Безплатно! Wi-Fi интернет е наличен в хотелските стаи и е без заплащане.</characteristic>
				</service>	
				
				<service>
					Паркинг
					<characteristic type="free">Безплатно! Безплатен частен паркинг е достъпен на място (резервация не е необходима).</characteristic>
					<characteristic>Охраняем паркинг</characteristic>
				</service>	
				
				<service>
					Услуги
					<characteristic>Ежедневно подреждане на стаята</characteristic>
					<characteristic>Обща TV зала</characteristic>
					<characteristic>Факс/Копирни услуги</characteristic>
					<characteristic>Пакетиран обяд</characteristic>
					<characteristic>Гладене (допълнително заплащане)</characteristic>
					<characteristic>ВИП услуги</characteristic>
					<characteristic>Пералня (допълнително заплащане)</characteristic>
					<characteristic>Денонощна рецепция</characteristic>
					<characteristic>Рум-сървиз</characteristic>
				</service>

				<service>
					Общи
					<characteristic>Климатик</characteristic>
					<characteristic>Отопление</characteristic>
					<characteristic>Сейф (допълнително заплащане)</characteristic>
					<characteristic>Семейни стаи</characteristic>
				</service>	
				
				<service>
					Политика за пушене
					<characteristic>Стаи за непушачи</characteristic>
				</service>

				<service>
					Персоналът говори няколко езика
					<characteristic>английски</characteristic>
					<characteristic>български</characteristic>
				</service>
				
			</more_info>
			<rooms>
				<rooms_description>
					Всички стаи са оборудвани с климатик, плоскоекранен телевизор с кабелни канали и минибар. Включват също собствена баня с вана или душ и сешоар.
					Гостите на хотел History могат да релаксират в градината. На разположение са 24-часова рецепция, тераса и ресторант, предлагащ френска и италианска кухня.
				</rooms_description>
				<rooms_images>
					<room_image type="1">
						<image_src href="historyRoom1"/>
					</room_image>
					<room_image type="2">
						<image_src href="historyRoom2"/>
					</room_image>
				</rooms_images>
				<room>
					<type>Голяма стая с 2 отделни легла</type>
					<price>
						<season>
							<all>100 лв.</all>
						</season>
					</price>
				</room>
				<room>
					<type>Студио</type>
					<price>
						<season>
							<all>120 лв.</all>
						</season>
					</price>
				</room>
				<room>
					<type>Двойна делукс стая</type>
					<price>
						<season>
							<all>120 лв.</all>
						</season>
					</price>
				</room>
				<room>
					<type>Суит с изглед към градина</type>
					<price>
						<season>
							<all>140 лв.</all>
						</season>
					</price>
				</room>
			</rooms>
			<image>
				<src href="history"/>
			</image>
		</hotel>
		
<!--============================LionBansko========================================-->
		
		<hotel hotelID="LionBansko" chainRef = "Lion" regionRef = "BA">
			<hotel_name>Hotel Lion Bansko</hotel_name>
			<category>4-звезден</category>
			<hotel_type>СПА</hotel_type>
			<address>
				<city>Банско</city>
				<street>Ул. Георги Настев</street>
			</address>
			<phone>+359 7498 68 00</phone>
			<email> bansko@hotelslion.bg</email>
			<site>www.bansko.hotelslion.bg/</site>
			<description>
